services:

  myimage:
    image: devapp:v1
    build: 
      context: ../
      dockerfile: dockerfile-dev
    container_name: myapp
    ports:
      - "8085:5000"

  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8086:80"
    depends_on:
      - myimage
    volumes:
      - ../files/:/usr/local/apache2/htdocs/
  